### PR TITLE
All ServerBuilder's setters return 'this'

### PR DESCRIPTION
**Pull request by nyukhalov**

### CODE REVIEW

**Comment by nmihajlovski** [comment]
Sorry for waiting, it took me some time to set a proper CLA management for Rapidoid.

**Comment by nyukhalov** [comment]
I've signed the CLA, but the check is still pending...

**Comment by nyukhalov** [comment]
Force pushed the branch to restart checking. Looks like it works now.

**Comment by nmihajlovski** [comment]
Thanks for your contribution!

**Pull request merged**
