### PR TITLE
#99 Added support for xml responses

### PR DESCRIPTION
**Pull request by cyterdan**

### CODE REVIEW

**Comment by nmihajlovski** [comment]
@cyterdan Thanks for this PR!

I created a separate branch `xml` for it, so I will resolve the conflicts after merging.

Please don't forget to sign the CLA agreement, it is a standard one - based on the Apache CLA.

**Comment by nmihajlovski** [comment]
I am going to make massive refactoring on the whole code base soon. That will introduce many conflicts with your changes, and would make merging much harder.

@cyterdan Are you abandoning this PR? Please let me know what your thoughts are.

**Comment by cyterdan** [comment]
sorry, missed your previous message for some reason. signed the CLA.

**Comment by nmihajlovski** [comment]
Thanks again for this very nice contribution!

**Pull request merged**
